// The canonical Technology catalog. CV scanning can only ever surface technologies that
// exist here (see helpers/cvTechnologyMatcher.js), so this list is what decides how much of
// a real CV gets recognized — keep it broad enough to cover the mainstream stacks interns
// actually list. A skill with no entry below is invisible to the CV scan no matter how it is
// written. Languages and tooling sit alongside frameworks on purpose: interns list all of
// them on a CV, and a mentor can meaningfully assess readiness on any of them. Whole-discipline
// entries that duplicate a Position name ("DevOps", "Data Engineering", "Data Science",
// "Machine Learning") do NOT belong here — those are specializations (server/models/Position.js),
// not technologies, and createTechnology/createPosition now reject that overlap going forward
// (see helpers/roleCatalog.js). Narrower practice labels that don't name a specialization
// outright ("Manual QA", "Test Automation", "Wireframing", "Penetration Testing") are still fine.
//
// Adding an entry: give it an explicit `slug` whenever slugify(name) would be lossy or
// collide (`C#` and `C++` both slugify to `c`). Then add the CV aliases for that slug in
// helpers/cvTechnologyMatcher.js, and optionally a brand logo in
// frontend/src/helpers/technologyIcons.jsx. Finish with `npm run seed:technologies` to
// backfill databases that were already seeded — a non-destructive upsert.
//
// Slugs are the stable key — ReadinessFlags, CV aliases and icons all reference them, so
// never rename one in place. To replace a coarse entry with granular ones, add the new entries
// here and retire the old row with `npm run cleanup:superseded-technologies` (see
// retireSupersededTechnologies.js); left active, both match the same CV line and one skill is
// auto-declared as several technologies.
//
// Entries may carry `category: 'ai'`, which puts them in the AI skills catalog instead of the
// technology one — a separate search box and a separate section on the intern's page, same
// declaration, assessment and staffing behaviour everywhere else. Omitting it means general,
// which is what every non-AI entry does. See server/constants/technologies.js.
//
// Groups below are for human readability only; the API sorts by name, and `category` — NOT the
// group a row sits in — is what splits the two catalogs. Entries that predate
// the "Languages"/"Databases" groups keep their original section. The Design & UX, Security,
// Game development and Embedded & hardware groups exist because the Position catalog
// (seeder/defaultPositions.js) names those four tracks and the catalog carried nothing an
// intern on any of them could declare — see context/current-feature.md.

module.exports = [
  // —— Languages ——
  { name: 'JavaScript' },
  { name: 'TypeScript' },
  { name: 'Python' },
  { name: 'Java' },
  { name: 'C#', slug: 'csharp' },
  { name: 'C', slug: 'c' },
  { name: 'PHP' },
  { name: 'Ruby' },
  { name: 'Scala' },
  { name: 'Elixir' },
  { name: 'Dart' },
  { name: 'R', slug: 'r' },
  { name: 'SQL' },
  { name: 'Objective-C', slug: 'objective-c' },
  { name: 'Perl' },
  { name: 'Lua' },
  { name: 'Haskell' },
  { name: 'Clojure' },
  { name: 'Erlang' },
  { name: 'F#', slug: 'fsharp' },
  { name: 'Groovy' },
  { name: 'Julia' },
  { name: 'Solidity' },
  { name: 'MATLAB' },
  { name: 'Assembly' },
  { name: 'Bash' },
  { name: 'PowerShell' },
  { name: 'Visual Basic', slug: 'visual-basic' },

  // —— Frontend ——
  { name: 'React' },
  { name: 'Angular' },
  { name: 'Vue.js', slug: 'vue-js' },
  { name: 'Next.js', slug: 'next-js' },
  { name: 'Nuxt.js', slug: 'nuxt-js' },
  { name: 'Svelte' },
  { name: 'Astro' },
  { name: 'SolidJS', slug: 'solidjs' },
  { name: 'Redux' },
  { name: 'jQuery' },
  { name: 'HTML' },
  { name: 'CSS' },
  { name: 'Sass' },
  { name: 'Tailwind CSS', slug: 'tailwind-css' },
  { name: 'Bootstrap' },
  { name: 'Material UI', slug: 'material-ui' },
  { name: 'Remix' },
  { name: 'Gatsby' },
  { name: 'Qwik' },
  { name: 'Preact' },
  { name: 'Ember.js', slug: 'ember-js' },
  { name: 'Alpine.js', slug: 'alpine-js' },
  { name: 'Web Components', slug: 'web-components' },
  { name: 'WebAssembly' },
  { name: 'Progressive Web Apps', slug: 'progressive-web-apps' },
  { name: 'Electron' },
  { name: 'Zustand' },
  { name: 'TanStack Query', slug: 'tanstack-query' },
  { name: 'React Router', slug: 'react-router' },
  { name: 'RxJS', slug: 'rxjs' },
  { name: 'styled-components', slug: 'styled-components' },
  { name: 'Chakra UI', slug: 'chakra-ui' },
  { name: 'Ant Design', slug: 'ant-design' },
  { name: 'shadcn/ui', slug: 'shadcn-ui' },
  { name: 'Radix UI', slug: 'radix-ui' },
  { name: 'Less' },
  { name: 'D3.js', slug: 'd3-js' },
  { name: 'Chart.js', slug: 'chart-js' },
  { name: 'Framer Motion', slug: 'framer-motion' },

  // —— Backend ——
  { name: 'Node.js', slug: 'node-js' },
  { name: 'Express.js', slug: 'express-js' },
  { name: 'NestJS', slug: 'nestjs' },
  { name: 'Spring Boot', slug: 'spring-boot' },
  { name: '.NET', slug: 'dotnet' },
  { name: 'Django' },
  { name: 'FastAPI' },
  { name: 'Flask' },
  { name: 'Go' },
  { name: 'Laravel' },
  { name: 'Symfony' },
  { name: 'Ruby on Rails', slug: 'ruby-on-rails' },
  { name: 'GraphQL' },
  { name: 'Fastify' },
  { name: 'Koa' },
  { name: 'Deno' },
  { name: 'Bun' },
  { name: 'tRPC', slug: 'trpc' },
  { name: 'Quarkus' },
  { name: 'Micronaut' },
  { name: 'Blazor' },
  { name: 'Hibernate' },
  { name: 'Entity Framework', slug: 'entity-framework' },
  { name: 'Prisma' },
  { name: 'Sequelize' },
  { name: 'TypeORM', slug: 'typeorm' },
  { name: 'Strapi' },
  { name: 'WordPress' },
  { name: 'Drupal' },
  { name: 'Shopify' },
  { name: 'REST API', slug: 'rest-api' },
  { name: 'gRPC', slug: 'grpc' },
  { name: 'WebSockets' },
  { name: 'Socket.IO', slug: 'socket-io' },
  { name: 'RabbitMQ' },
  { name: 'Apache Tomcat', slug: 'apache-tomcat' },
  { name: 'Apache HTTP Server', slug: 'apache-http-server' },
  { name: 'Swagger', slug: 'swagger' },

  // —— Databases ——
  { name: 'PostgreSQL' },
  { name: 'MySQL' },
  { name: 'MongoDB' },
  { name: 'Redis' },
  { name: 'Microsoft SQL Server', slug: 'sql-server' },
  { name: 'Oracle Database', slug: 'oracle-database' },
  { name: 'Elasticsearch' },
  { name: 'SQLite' },
  { name: 'MariaDB' },
  { name: 'Apache Cassandra', slug: 'apache-cassandra' },
  { name: 'Neo4j' },
  { name: 'Amazon DynamoDB', slug: 'dynamodb' },
  { name: 'Firebase' },
  { name: 'Supabase' },
  { name: 'ClickHouse' },
  { name: 'InfluxDB' },
  { name: 'CouchDB' },
  { name: 'Snowflake' },
  { name: 'Google BigQuery', slug: 'bigquery' },
  { name: 'Amazon Redshift', slug: 'redshift' },

  // —— Mobile ——
  { name: 'Kotlin' },
  { name: 'Swift' },
  { name: 'Android' },
  { name: 'iOS', slug: 'ios' },
  { name: 'React Native', slug: 'react-native' },
  { name: 'Flutter' },
  { name: 'Ionic' },
  { name: 'Xamarin' },
  { name: 'Expo' },
  { name: 'Capacitor' },
  { name: 'Kotlin Multiplatform', slug: 'kotlin-multiplatform' },

  // —— Data & analytics ——
  { name: 'Pandas' },
  { name: 'NumPy' },
  { name: 'Apache Spark', slug: 'apache-spark' },
  { name: 'Apache Airflow', slug: 'apache-airflow' },
  { name: 'Apache Kafka', slug: 'apache-kafka' },
  { name: 'Power BI', slug: 'power-bi' },
  { name: 'Tableau' },
  { name: 'Apache Hadoop', slug: 'apache-hadoop' },
  { name: 'Apache Flink', slug: 'apache-flink' },
  { name: 'Databricks' },
  { name: 'dbt', slug: 'dbt' },
  { name: 'Looker' },
  { name: 'Qlik Sense', slug: 'qlik-sense' },
  { name: 'Matplotlib' },
  { name: 'SciPy' },

  // —— ML & AI ——
  { name: 'TensorFlow' },
  { name: 'PyTorch' },
  { name: 'scikit-learn', slug: 'scikit-learn' },
  { name: 'Keras' },
  { name: 'OpenCV' },
  { name: 'Hugging Face', slug: 'hugging-face' },
  { name: 'MLflow' },
  { name: 'XGBoost' },
  { name: 'Computer Vision', slug: 'computer-vision' },
  { name: 'Natural Language Processing', slug: 'nlp' },
  { name: 'Stable Diffusion', slug: 'stable-diffusion' },
  { name: 'Vector Databases', slug: 'vector-databases' },

  // —— AI skills ——
  // The `ai` category, and the only group that carries one — everything above is general by
  // default. These are the tools an engineer works *with* rather than the ML stack they
  // build: coding agents and assistant IDEs, the LLM APIs and agent SDKs behind them, and
  // the practices that come with both. The line against ML & AI above is who does the
  // learning — PyTorch trains a model, Claude Code uses one.
  //
  // Slugs are the stable key here too, so a rebrand ("Codeium" → "Windsurf") is a NAME edit,
  // never a slug edit. Six entries below (LangChain, OpenAI API, LLMs, RAG, Prompt
  // Engineering, Ollama) moved here from ML & AI keeping their original slugs, so every
  // existing declaration and readiness flag on them still resolves — they simply list under
  // AI skills now.
  { name: 'Claude Code', slug: 'claude-code', category: 'ai' },
  { name: 'Cursor', slug: 'cursor', category: 'ai' },
  { name: 'GitHub Copilot', slug: 'github-copilot', category: 'ai' },
  {
    name: 'GitHub Copilot Agent Mode',
    slug: 'github-copilot-agent-mode',
    category: 'ai',
  },
  { name: 'Windsurf', slug: 'windsurf', category: 'ai' },
  { name: 'Gemini CLI', slug: 'gemini-cli', category: 'ai' },
  { name: 'OpenAI Codex', slug: 'openai-codex', category: 'ai' },
  { name: 'Cline', slug: 'cline', category: 'ai' },
  { name: 'Aider', slug: 'aider', category: 'ai' },
  { name: 'Devin', slug: 'devin', category: 'ai' },
  { name: 'JetBrains AI Assistant', slug: 'jetbrains-ai-assistant', category: 'ai' },
  { name: 'Amazon Q Developer', slug: 'amazon-q-developer', category: 'ai' },
  { name: 'Replit Agent', slug: 'replit-agent', category: 'ai' },
  { name: 'Lovable', slug: 'lovable', category: 'ai' },
  { name: 'Bolt.new', slug: 'bolt-new', category: 'ai' },
  { name: 'v0', slug: 'v0', category: 'ai' },
  { name: 'AI Code Review', slug: 'ai-code-review', category: 'ai' },
  { name: 'ChatGPT', slug: 'chatgpt', category: 'ai' },
  { name: 'Perplexity', slug: 'perplexity', category: 'ai' },
  { name: 'Anthropic Claude API', slug: 'anthropic-claude-api', category: 'ai' },
  { name: 'Google Gemini API', slug: 'google-gemini-api', category: 'ai' },
  { name: 'OpenAI API', slug: 'openai-api', category: 'ai' },
  { name: 'Claude Agent SDK', slug: 'claude-agent-sdk', category: 'ai' },
  { name: 'OpenAI Agents SDK', slug: 'openai-agents-sdk', category: 'ai' },
  { name: 'Vercel AI SDK', slug: 'vercel-ai-sdk', category: 'ai' },
  { name: 'Model Context Protocol', slug: 'mcp', category: 'ai' },
  { name: 'Agent Skills', slug: 'agent-skills', category: 'ai' },
  { name: 'LangChain', slug: 'langchain', category: 'ai' },
  { name: 'LangGraph', slug: 'langgraph', category: 'ai' },
  { name: 'LlamaIndex', slug: 'llamaindex', category: 'ai' },
  { name: 'AI Agent Orchestration', slug: 'ai-agent-orchestration', category: 'ai' },
  { name: 'Large Language Models', slug: 'large-language-models', category: 'ai' },
  { name: 'Retrieval-Augmented Generation', slug: 'rag', category: 'ai' },
  { name: 'Prompt Engineering', slug: 'prompt-engineering', category: 'ai' },
  { name: 'LLM Evaluation', slug: 'llm-evaluation', category: 'ai' },
  { name: 'Ollama', slug: 'ollama', category: 'ai' },

  // —— QA ——
  { name: 'Manual QA', slug: 'manual-qa' },
  { name: 'Test Automation', slug: 'test-automation' },
  { name: 'Selenium' },
  { name: 'Cypress' },
  { name: 'Playwright' },
  { name: 'Jest' },
  { name: 'JUnit' },
  { name: 'Postman' },
  { name: 'Vitest' },
  { name: 'Mocha' },
  { name: 'Testing Library', slug: 'testing-library' },
  { name: 'TestNG', slug: 'testng' },
  { name: 'Cucumber' },
  { name: 'REST Assured', slug: 'rest-assured' },
  { name: 'Appium' },
  { name: 'Robot Framework', slug: 'robot-framework' },
  { name: 'Apache JMeter', slug: 'jmeter' },
  { name: 'k6', slug: 'k6' },
  { name: 'Insomnia' },
  { name: 'SonarQube' },
  { name: 'Performance Testing', slug: 'performance-testing' },
  { name: 'API Testing', slug: 'api-testing' },

  // —— DevOps & cloud ——
  { name: 'Docker' },
  { name: 'Kubernetes' },
  { name: 'AWS' },
  { name: 'Microsoft Azure', slug: 'azure' },
  { name: 'Google Cloud', slug: 'google-cloud' },
  { name: 'Terraform' },
  { name: 'Ansible' },
  { name: 'Jenkins' },
  { name: 'GitHub Actions', slug: 'github-actions' },
  { name: 'GitLab CI', slug: 'gitlab-ci' },
  { name: 'Linux' },
  { name: 'Nginx' },
  { name: 'Helm' },
  { name: 'Argo CD', slug: 'argo-cd' },
  { name: 'Prometheus' },
  { name: 'Grafana' },
  { name: 'Kibana' },
  { name: 'Logstash' },
  { name: 'Datadog' },
  { name: 'Splunk' },
  { name: 'Sentry' },
  { name: 'New Relic', slug: 'new-relic' },
  { name: 'CircleCI', slug: 'circleci' },
  { name: 'Azure DevOps', slug: 'azure-devops' },
  { name: 'Bitbucket Pipelines', slug: 'bitbucket-pipelines' },
  { name: 'Vagrant' },
  { name: 'Pulumi' },
  { name: 'Serverless Framework', slug: 'serverless-framework' },
  { name: 'AWS Lambda', slug: 'aws-lambda' },
  { name: 'Cloudflare' },
  { name: 'Vercel' },
  { name: 'Netlify' },
  { name: 'Heroku' },
  { name: 'DigitalOcean' },

  // —— Design & UX ——
  { name: 'Figma' },
  { name: 'Adobe XD', slug: 'adobe-xd' },
  { name: 'Sketch' },
  { name: 'Adobe Photoshop', slug: 'adobe-photoshop' },
  { name: 'Adobe Illustrator', slug: 'adobe-illustrator' },
  { name: 'Adobe After Effects', slug: 'adobe-after-effects' },
  { name: 'InVision', slug: 'invision' },
  { name: 'Framer' },
  { name: 'Canva' },
  { name: 'Miro' },
  { name: 'Axure RP', slug: 'axure-rp' },
  { name: 'Wireframing' },
  { name: 'Prototyping' },
  { name: 'User Research', slug: 'user-research' },
  { name: 'Usability Testing', slug: 'usability-testing' },
  { name: 'Design Systems', slug: 'design-systems' },
  { name: 'Web Accessibility', slug: 'web-accessibility' },

  // —— Security ——
  { name: 'Wireshark' },
  { name: 'Burp Suite', slug: 'burp-suite' },
  { name: 'Kali Linux', slug: 'kali-linux' },
  { name: 'Nmap' },
  { name: 'Metasploit' },
  { name: 'OWASP ZAP', slug: 'owasp-zap' },
  { name: 'Ghidra' },
  { name: 'HashiCorp Vault', slug: 'hashicorp-vault' },
  { name: 'Keycloak' },
  { name: 'OAuth 2.0', slug: 'oauth' },
  { name: 'Penetration Testing', slug: 'penetration-testing' },
  { name: 'Network Security', slug: 'network-security' },
  { name: 'Cryptography' },
  { name: 'SIEM', slug: 'siem' },
  { name: 'Incident Response', slug: 'incident-response' },
  { name: 'Threat Modeling', slug: 'threat-modeling' },
  { name: 'Malware Analysis', slug: 'malware-analysis' },
  { name: 'Vulnerability Assessment', slug: 'vulnerability-assessment' },

  // —— Game development ——
  { name: 'Unity' },
  { name: 'Unreal Engine', slug: 'unreal-engine' },
  { name: 'Godot' },
  { name: 'Blender' },
  { name: 'Three.js', slug: 'three-js' },
  { name: 'Phaser' },
  { name: 'PixiJS', slug: 'pixijs' },

  // —— Embedded & hardware ——
  { name: 'Arduino' },
  { name: 'Raspberry Pi', slug: 'raspberry-pi' },
  { name: 'STM32', slug: 'stm32' },
  { name: 'ESP32', slug: 'esp32' },
  { name: 'FreeRTOS' },
  { name: 'Zephyr RTOS', slug: 'zephyr-rtos' },
  { name: 'VHDL' },
  { name: 'Verilog' },
  { name: 'CAN Bus', slug: 'can-bus' },
  { name: 'PLC Programming', slug: 'plc-programming' },
  { name: 'Embedded C', slug: 'embedded-c' },
  { name: 'MQTT' },

  // —— Tooling ——
  { name: 'Git' },
  { name: 'GitHub' },
  { name: 'GitLab' },
  { name: 'Bitbucket' },
  { name: 'Jira' },
  { name: 'Confluence' },
  { name: 'Trello' },
  { name: 'Vite' },
  { name: 'Webpack' },
  { name: 'Babel' },
  { name: 'ESLint', slug: 'eslint' },
  { name: 'Storybook' },
  { name: 'Maven' },
  { name: 'Gradle' },
  { name: 'Nx', slug: 'nx' },
  { name: 'Turborepo' },

  // —— Practices ——
  { name: 'Microservices' },
  { name: 'CI/CD', slug: 'ci-cd' },
  { name: 'Test-Driven Development', slug: 'tdd' },
  { name: 'Scrum' },
  { name: 'Kanban' },

  // —— Specialized engineering ——
  { name: 'C++', slug: 'cpp' },
  { name: 'Rust' },
];
