module.exports = [
  // —— Languages ——
  { name: 'JavaScript' },
  { name: 'TypeScript' },
  { name: 'Python' },
  { name: 'Java' },
  { name: 'C#', slug: 'csharp' },
  { name: 'C++', slug: 'cpp' },
  { name: 'Go' },
  { name: 'Rust' },
  { name: 'Kotlin' },
  { name: 'Swift' },
  { name: 'Scala' },
  { name: 'Ruby' },
  { name: 'PHP' },
  { name: 'Dart' },
  { name: 'R' },
  { name: 'Bash' },
  { name: 'PowerShell' },
  { name: 'SQL' },

  // —— Frontend ——
  { name: 'HTML' },
  { name: 'CSS' },
  { name: 'Sass' },
  { name: 'React' },
  { name: 'Angular' },
  { name: 'Vue.js', slug: 'vue-js' },
  { name: 'Next.js', slug: 'next-js' },
  { name: 'Nuxt.js', slug: 'nuxt-js' },
  { name: 'Svelte' },
  { name: 'Redux' },
  { name: 'Zustand' },
  { name: 'TanStack Query', slug: 'tanstack-query' },
  { name: 'Tailwind CSS', slug: 'tailwind-css' },
  { name: 'Material UI', slug: 'material-ui' },
  { name: 'Ant Design', slug: 'ant-design' },
  { name: 'Webpack' },
  { name: 'Vite' },
  { name: 'Web Accessibility', slug: 'web-accessibility' },

  // —— Backend & APIs ——
  { name: 'Node.js', slug: 'node-js' },
  { name: 'Express' },
  { name: 'NestJS' },
  { name: 'Django' },
  { name: 'Flask' },
  { name: 'FastAPI' },
  { name: 'Spring Boot', slug: 'spring-boot' },
  { name: '.NET', slug: 'dotnet' },
  { name: 'ASP.NET Core', slug: 'aspnet-core' },
  { name: 'Hibernate' },
  { name: 'Ruby on Rails', slug: 'ruby-on-rails' },
  { name: 'Laravel' },
  { name: 'GraphQL' },
  { name: 'REST APIs', slug: 'rest-apis' },
  { name: 'gRPC' },
  { name: 'Microservices' },
  { name: 'Event-Driven Architecture', slug: 'event-driven-architecture' },
  { name: 'Domain-Driven Design', slug: 'domain-driven-design' },

  // —— Mobile ——
  { name: 'Android' },
  { name: 'iOS' },
  { name: 'React Native', slug: 'react-native' },
  { name: 'Flutter' },
  { name: 'Jetpack Compose', slug: 'jetpack-compose' },
  { name: 'SwiftUI' },
  { name: 'Xcode' },

  // —— Databases & storage ——
  { name: 'PostgreSQL' },
  { name: 'MySQL' },
  { name: 'Microsoft SQL Server', slug: 'microsoft-sql-server' },
  { name: 'MongoDB' },
  { name: 'Redis' },
  { name: 'Elasticsearch' },
  { name: 'DynamoDB' },
  { name: 'Cassandra' },
  { name: 'Neo4j' },
  { name: 'PostGIS' },
  { name: 'SQLite' },
  { name: 'Oracle Database', slug: 'oracle-database' },
  { name: 'Snowflake' },
  { name: 'Google BigQuery', slug: 'google-bigquery' },
  { name: 'Amazon Redshift', slug: 'amazon-redshift' },
  { name: 'NoSQL' },
  { name: 'SQLAlchemy' },

  // —— Data engineering & analytics ——
  { name: 'Data Engineering', slug: 'data-engineering' },
  { name: 'Data Warehousing', slug: 'data-warehousing' },
  { name: 'ETL' },
  { name: 'Apache Spark', slug: 'apache-spark' },
  { name: 'Apache Kafka', slug: 'apache-kafka' },
  { name: 'Apache Airflow', slug: 'apache-airflow' },
  { name: 'Apache Flink', slug: 'apache-flink' },
  { name: 'Apache Hadoop', slug: 'apache-hadoop' },
  { name: 'dbt' },
  { name: 'Databricks' },
  { name: 'Delta Lake', slug: 'delta-lake' },
  { name: 'Pandas' },
  { name: 'NumPy' },
  { name: 'PySpark' },
  { name: 'Power BI', slug: 'power-bi' },
  { name: 'Tableau' },
  { name: 'Looker' },
  { name: 'Metabase' },
  { name: 'Plotly' },
  { name: 'OLAP' },
  { name: 'OLTP' },

  // —— AI / ML ——
  { name: 'Data Science', slug: 'data-science' },
  { name: 'Machine Learning', slug: 'machine-learning' },
  { name: 'AI/ML Engineering', slug: 'ai-ml-engineering' },
  { name: 'TensorFlow' },
  { name: 'PyTorch' },
  { name: 'scikit-learn', slug: 'scikit-learn' },
  { name: 'LangChain' },
  { name: 'LLMs' },
  { name: 'Generative AI', slug: 'generative-ai' },
  { name: 'NLP' },
  { name: 'Computer Vision', slug: 'computer-vision' },
  { name: 'MLOps' },
  { name: 'Kubeflow' },

  // —— QA & testing ——
  { name: 'QA' },
  { name: 'Manual Testing', slug: 'manual-testing' },
  { name: 'Test Automation', slug: 'test-automation' },
  { name: 'API Testing', slug: 'api-testing' },
  { name: 'Performance Testing', slug: 'performance-testing' },
  { name: 'Selenium' },
  { name: 'Cypress' },
  { name: 'Playwright' },
  { name: 'Jest' },
  { name: 'pytest' },
  { name: 'JUnit' },
  { name: 'TestNG' },
  { name: 'Cucumber' },
  { name: 'Postman' },
  { name: 'SoapUI' },
  { name: 'JMeter' },
  { name: 'k6' },
  { name: 'SonarQube' },
  { name: 'TestRail' },

  // —— DevOps, cloud & platform ——
  { name: 'DevOps' },
  { name: 'Site Reliability Engineering', slug: 'site-reliability-engineering' },
  { name: 'AWS' },
  { name: 'Microsoft Azure', slug: 'microsoft-azure' },
  { name: 'Google Cloud', slug: 'google-cloud' },
  { name: 'Docker' },
  { name: 'Kubernetes' },
  { name: 'Terraform' },
  { name: 'Ansible' },
  { name: 'Puppet' },
  { name: 'Chef' },
  { name: 'Jenkins' },
  { name: 'GitLab CI', slug: 'gitlab-ci' },
  { name: 'GitHub Actions', slug: 'github-actions' },
  { name: 'Argo CD', slug: 'argo-cd' },
  { name: 'Helm' },
  { name: 'Prometheus' },
  { name: 'Grafana' },
  { name: 'ELK Stack', slug: 'elk-stack' },
  { name: 'Kibana' },
  { name: 'Datadog' },
  { name: 'Linux' },
  { name: 'Nginx' },
  { name: 'Istio' },
  { name: 'Infrastructure as Code', slug: 'infrastructure-as-code' },
  { name: 'CI/CD', slug: 'ci-cd' },

  // —— Security & identity ——
  { name: 'OAuth' },
  { name: 'Auth0' },
  { name: 'Keycloak' },
  { name: 'Application Security', slug: 'application-security' },
  { name: 'Cloud Security', slug: 'cloud-security' },

  // —— Tooling & delivery ——
  { name: 'Git' },
  { name: 'GitHub' },
  { name: 'GitLab' },
  { name: 'Bitbucket' },
  { name: 'Jira' },
  { name: 'Confluence' },
  { name: 'Gradle' },
  { name: 'Maven' },
  { name: 'Figma' },
  { name: 'Agile' },
  { name: 'Scrum' },

  // —— Integrations & platforms (Symphony client stack) ——
  { name: 'Stripe' },
  { name: 'Twilio' },
  { name: 'Shopify' },
  { name: 'Mixpanel' },

  // —— Architecture & leadership tracks ——
  { name: 'Solutions Architecture', slug: 'solutions-architecture' },
  { name: 'Product Management', slug: 'product-management' },
  { name: 'UX Design', slug: 'ux-design' },
  { name: 'UI Design', slug: 'ui-design' },
  { name: 'Technical Writing', slug: 'technical-writing' },
];
