module.exports = [
  { name: 'Frontend Engineer', slug: 'frontend-engineer' },
  { name: 'Backend Engineer', slug: 'backend-engineer' },
  { name: 'Fullstack Engineer', slug: 'fullstack-engineer' },
  { name: 'Mobile Engineer', slug: 'mobile-engineer' },
  { name: 'Data Engineer', slug: 'data-engineer' },
  { name: 'ML Engineer', slug: 'ml-engineer' },
  { name: 'AI Engineer', slug: 'ai-engineer' },
  { name: 'UI/UX Designer', slug: 'ui-ux-designer' },
  { name: 'DevOps Engineer', slug: 'devops-engineer' },
  { name: 'QA Engineer', slug: 'qa-engineer' },
  { name: 'Cybersecurity Engineer', slug: 'cybersecurity-engineer' },
  { name: 'Cloud Architect', slug: 'cloud-architect' },
  { name: 'Database Administrator', slug: 'database-administrator' },
  { name: 'Game Developer', slug: 'game-developer' },
  { name: 'Embedded Systems Engineer', slug: 'embedded-systems-engineer' },
];
